FROM ubuntu:rolling

LABEL description="A docker image for kratos"
LABEL maintainer="keyi@cs.stanford.edu"

RUN apt-get update && \
    apt-get install -y --no-install-recommends git gcc-8 g++-8 python3 \
            python3-pip verilator cmake build-essential python3-dev \
            python3-setuptools make python3-wheel file valgrind && \
        apt-get clean

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip
